---
title: "reg"
output: html_document
date: '2022-06-20'
---

```{r}
library(dplyr)
library(ggplot2)
```

```{r load dataset}
data <- read.csv('bike_sharing.csv')
```

```{r split datetime column}
library(lubridate)
day <- day(dmy_hm(data$datetime))
month <- month(dmy_hm(data$datetime))
year <- year(dmy_hm(data$datetime))
hour <- hour(dmy_hm(data$datetime))

library(tibble)
data <- add_column(data, day=day, .after="datetime")
data <- add_column(data, month=month, .after="day")
data <- add_column(data, year=year, .after="month")
data <- add_column(data, hour=hour, .after="year")

data$month <- as.factor(data$month)
data$year <- as.factor(data$year)
```

```{r rename categorical columns}
data$season <- as.factor(data$season)
levels(data$season)[c(1,2,3,4)] <- c("winter", "spring", "summer", "fall")

data$weather <- as.factor(data$weather)
levels(data$weather)[c(1,2,3,4)] <- c("good", "normal", "bad", "very bad")

data$workingday <- ifelse(data$workingday==1, "yes", "no")
data$workingday <- as.factor(data$workingday)

data$holiday <- ifelse(data$holiday==1, "yes", "no")
data$holiday <- as.factor(data$holiday)
```

```{r}
library(car)

reg_model <- lm(count ~ ., data=data[,-c(1, 15)])
vif(reg_model)
```

```{r categorical & numerical columns}
cat_columns <- c("season", "holiday", "workingday", "weather")

num_columns <- c("day", "hour", "atemp", "humidity", "windspeed")
```

# Pemodelan
```{r normalize & accuracy function}
normalize <- function(x){
 (x-min(x))/(max(x)-min(x))
}

accuracy <- function(x){
  print(sum(diag(x)))
  print(sum(rowSums(x)))
  sum(diag(x)/(sum(rowSums(x))))*100
 }
```

```{r normalize numerical columns}
data[num_columns] <- as.data.frame(lapply(data[num_columns], normalize))
```

```{r}
linear_model <- lm(count ~ day + hour + atemp + humidity + windspeed + season + holiday + workingday + weather, data=data)

summary(linear_model)
```